using System;
using System.Collections.Generic;

namespace CFixer.Helpers
{
    internal static class Localization
    {
        private static readonly Dictionary<string, string> ExactTranslations =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["Issues"] = "문제 해결",
                ["System"] = "시스템",
                ["MS Edge"] = "MS Edge",
                ["UI"] = "UI",
                ["Gaming"] = "게이밍",
                ["Privacy"] = "개인정보",
                ["Ads"] = "광고",
                ["AI"] = "AI",
                ["Plugins"] = "플러그인",
                ["General"] = "일반",

                ["Disable File Explorer Ads"] = "파일 탐색기 광고 끄기",
                ["Disable Finish Setup Ads"] = "설정 마무리 광고 끄기",
                ["Disable Lock Screen Tips and Ads"] = "잠금 화면 팁 및 광고 끄기",
                ["Disable Personalized Ads"] = "개인 맞춤 광고 끄기",
                ["Disable Settings Ads"] = "설정 앱 광고 끄기",
                ["Disable Start menu Ads"] = "시작 메뉴 광고 끄기",
                ["Disable Tailored experiences"] = "맞춤형 경험 끄기",
                ["Disable General Tips and Ads"] = "일반 팁 및 광고 끄기",
                ["Disable Welcome Experience Ads"] = "시작 환영 화면 광고 끄기",
                ["Remove Ask Copilot from context menu"] = "컨텍스트 메뉴에서 Ask Copilot 제거",
                ["Disable Click to Do (Only Copilot+ PCs)"] = "Click to Do 끄기 (Copilot+ PC 전용)",
                ["Don't Show Copilot in Taskbar"] = "작업 표시줄에서 Copilot 숨기기",
                ["Turn off Recall in Windows 11"] = "Windows 11 Recall 끄기",
                ["Disable Browser sign in and sync services"] = "브라우저 로그인 및 동기화 서비스 끄기",
                ["Don't Show Sponsored links in new tab page"] = "새 탭 페이지의 스폰서 링크 숨기기",
                ["Disable Microsoft Edge as default browser"] = "기본 브라우저 변경 권유 끄기",
                ["Disable Access to Collections feature"] = "Collections 기능 끄기",
                ["Disable Shopping assistant"] = "쇼핑 도우미 끄기",
                ["Don't Show First Run Experience"] = "첫 실행 화면 숨기기",
                ["Disable Gamer Mode"] = "게이머 모드 끄기",
                ["Disable Copilot Symbol in Edge"] = "Edge에서 Copilot 아이콘 끄기",
                ["Don't Allow to Import of data from other browsers on each launch"] = "실행 시 다른 브라우저 데이터 가져오기 끄기",
                ["Disable Start Boost"] = "시작 부스트 끄기",
                ["Don't Show Quick links in new tab page"] = "새 탭 페이지의 빠른 링크 숨기기",
                ["Don't Submit user feedback option"] = "사용자 피드백 제출 옵션 숨기기",
                ["Disable Game DVR"] = "게임 DVR 끄기",
                ["Disable Power Throttling"] = "전원 스로틀링 끄기",
                ["Disable Visual Effects"] = "시각 효과 끄기",
                ["Basic Disk Cleanup"] = "기본 디스크 정리",
                ["Winget App Updates"] = "Winget 앱 업데이트",
                ["Disable activity history"] = "활동 기록 끄기",
                ["Disable location tracking"] = "위치 추적 끄기",
                ["Disable Privacy Settings Experience at sign-in"] = "로그인 시 개인정보 설정 화면 끄기",
                ["Turn off Telemetry data collection"] = "텔레메트리 수집 끄기",
                ["Show BSOD details instead of sad smiley"] = "슬픈 이모지 대신 BSOD 상세 정보 표시",
                ["Speed Up Menu Show Delay"] = "메뉴 표시 지연 줄이기",
                ["Disable Network Throttling"] = "네트워크 스로틀링 끄기",
                ["Speed Up Shutdown Time"] = "종료 시간 단축",
                ["Optimize System Responsiveness"] = "시스템 응답성 최적화",
                ["Enable End Task"] = "작업 끝내기 메뉴 활성화",
                ["Enable Verbose Logon status messages"] = "상세 로그인 상태 메시지 활성화",
                ["Disable Bing Search"] = "Bing 검색 끄기",
                ["Enable Dark Mode for Apps"] = "앱 다크 모드 활성화",
                ["Enable Dark Mode for System"] = "시스템 다크 모드 활성화",
                ["Show Full context menus in Windows 11"] = "Windows 11 전체 컨텍스트 메뉴 표시",
                ["Don't use personalized lock screen"] = "개인 맞춤 잠금 화면 사용 안 함",
                ["Disable Search Box Suggestions"] = "검색 상자 제안 끄기",
                ["Hide search box on taskbar"] = "작업 표시줄 검색 상자 숨기기",
                ["Hide Most used apps in start menu"] = "시작 메뉴의 자주 사용하는 앱 숨기기",
                ["Hide Task view button on taskbar"] = "작업 표시줄 작업 보기 버튼 숨기기",
                ["Disable Snap Assist Flyout"] = "스냅 도우미 플라이아웃 끄기",
                ["Pin more Apps on start menu"] = "시작 메뉴에 앱 더 많이 고정",
                ["Align Start button to left"] = "시작 버튼 왼쪽 정렬",
                ["Disable Transparency Effects"] = "투명 효과 끄기",

                ["This feature will disable ads in File Explorer."] = "파일 탐색기의 광고를 끕니다.",
                ["This feature will disable the \"Lets finish setting up your device\" and other advertising."] = "\"기기 설정을 마무리해 보세요\" 같은 설정 완료 광고를 끕니다.",
                ["This feature will disable tips and ads on the lock screen."] = "잠금 화면의 팁과 광고를 끕니다.",
                ["This feature will disable personalized ads."] = "개인 맞춤 광고를 끕니다.",
                ["This feature will disable ads in settings."] = "설정 앱의 광고를 끕니다.",
                ["This feature will disable ads in the start menu."] = "시작 메뉴의 광고를 끕니다.",
                ["Tailored Experiences allows Microsoft to get information from you to deliver personalized tips, ads, and recommendations. Many people would call this telemetry, or even spying."] = "맞춤형 경험은 개인화된 팁, 광고, 추천을 제공하기 위해 Microsoft가 사용자 정보를 활용하도록 합니다. 많은 사용자가 이를 텔레메트리 또는 과도한 추적으로 봅니다.",
                ["This feature will disable general tips and ads."] = "일반 팁과 광고를 끕니다.",
                ["This feature will disable ads in the welcome experience."] = "시작 환영 화면의 광고를 끕니다.",
                ["Blocks the 'Ask Copilot' entry in the Windows 11 context menu by disabling its Shell Extension."] = "셸 확장을 비활성화해 Windows 11 컨텍스트 메뉴의 'Ask Copilot' 항목을 숨깁니다.",
                ["Disables Click to Do entirely, including its context menu entry which uses on-device AI to suggest actions based on screen content. Only available on Copilot+ PCs with Windows 11 24H2 or newer."] = "화면 내용을 바탕으로 온디바이스 AI가 작업을 제안하는 Click to Do와 해당 컨텍스트 메뉴 항목을 완전히 비활성화합니다. Windows 11 24H2 이상이 설치된 Copilot+ PC에서만 사용할 수 있습니다.",
                ["This feature will disable Copilot in Taskbar."] = "작업 표시줄의 Copilot을 숨깁니다.",
                ["This will remove Recall from Windows 11 24H2"] = "Windows 11 24H2의 Recall 기능을 끕니다.",
                ["This setting controls whether a user can sign into Microsoft Edge with an account to use services such as sync and single sign on"] = "사용자가 Microsoft Edge에 계정으로 로그인해 동기화와 싱글 사인온 같은 서비스를 사용할 수 있는지 제어합니다.",
                ["Hide default top sites from the new tab page in Microsoft Edge"] = "Microsoft Edge 새 탭 페이지의 기본 상위 사이트를 숨깁니다.",
                ["Force Edge to stop asking to change default browser"] = "Microsoft Edge가 기본 브라우저 변경을 권유하지 않도록 합니다.",
                ["Enables users to access the Collections feature, allowing them to gather, organize, share, and export content more efficiently with Office integration"] = "Office 연동을 포함해 콘텐츠를 수집, 정리, 공유, 내보낼 수 있는 Collections 기능을 비활성화합니다.",
                ["Shopping in Microsoft Edge feature will automatically find you the best prices and coupons from across the web as you shop"] = "Microsoft Edge의 쇼핑 기능이 웹 전반에서 가격과 쿠폰을 자동으로 찾지 않도록 합니다.",
                ["Hide home screen and 'Getting Started' on initial launch (from version 80 onwards)"] = "초기 실행 시 홈 화면과 '시작하기' 화면을 숨깁니다. (버전 80 이상)",
                ["Microsoft Edge Gamer Mode allows gamers to personalize their browser with gaming themes and gives them the option of enabling Efficiency Mode for PC gaming, the Gaming feed on new tabs, sidebar apps for gamers, and more"] = "Microsoft Edge 게이머 모드는 게이밍 테마, 효율성 모드, 새 탭의 게임 피드, 사이드바 앱 등을 제공합니다. 이 기능을 비활성화합니다.",
                ["This feature will disable Copilot in Microsoft Edge."] = "Microsoft Edge의 Copilot을 비활성화합니다.",
                ["Allow import of data from other browsers on each Microsoft Edge launch"] = "Microsoft Edge를 실행할 때마다 다른 브라우저의 데이터를 가져오지 않도록 합니다.",
                ["Enables Microsoft Edge processes to initialize at operating system startup and restart in the background after the last browser window has been closed"] = "Microsoft Edge 프로세스가 운영체제 시작 시 미리 실행되거나 마지막 창을 닫은 뒤 백그라운드에서 다시 시작되지 않도록 합니다.",
                ["By default, when you open a new tab, you see a Bing search bar, Bing image of the day set as the page background. For supported websites, Quick Links on the New Tab page can display recent updates right in the tile"] = "기본적으로 새 탭을 열면 Bing 검색창과 Bing 오늘의 이미지, 빠른 링크가 표시됩니다. 이 기능을 숨깁니다.",
                ["Allow the submission of feedback, suggestions, or customer surveys, as well as reporting issues with the browser"] = "피드백, 제안, 설문 제출과 브라우저 문제 보고 옵션을 숨깁니다.",
                ["This feature will disable Game DVR."] = "게임 DVR을 비활성화합니다.",
                ["This feature will disable Power Throttling."] = "전원 스로틀링을 비활성화합니다.",
                ["This feature will disable visual effects in Windows."] = "Windows의 시각 효과를 비활성화합니다.",
                ["Deletes all temporary files from the user's Temp folder. Then, the built-in Disk Cleanup utility (cleanmgr) is run."] = "사용자 Temp 폴더의 임시 파일을 삭제한 뒤 기본 디스크 정리(cleanmgr)를 실행합니다.",
                ["Automatically searches for available app updates using the Windows package manager 'winget' and installs them in a new Windows Terminal window. It runs 'winget upgrade --include-unknown' to list all available updates, including manually installed apps, and then 'winget upgrade --all --include-unknown' to install them. No manual interaction is required."] = "Windows 패키지 관리자 'winget'로 사용 가능한 앱 업데이트를 찾고 새 Windows Terminal 창에서 설치합니다. 'winget upgrade --include-unknown'으로 목록을 확인한 뒤 'winget upgrade --all --include-unknown'으로 설치합니다.",
                ["Disable activity history (prevents Windows from tracking and storing your activity)"] = "활동 기록을 비활성화해 Windows가 사용 기록을 추적하고 저장하지 못하게 합니다.",
                ["Disable location tracking (prevents Windows from accessing your location)"] = "위치 추적을 비활성화해 Windows가 현재 위치에 접근하지 못하게 합니다.",
                ["This feature will disable Privacy Settings Experience at sign-in."] = "로그인 시 표시되는 개인정보 설정 경험 화면을 비활성화합니다.",
                ["This feature will turn off telemetry data collection and prevent the data from being sent to Microsoft."] = "텔레메트리 데이터 수집을 끄고 데이터가 Microsoft로 전송되지 않도록 합니다.",
                ["This method displays the full classic BSOD with technical error details instead of the simplified sad face version."] = "단순한 슬픈 얼굴 대신 기술 정보가 포함된 고전적인 전체 BSOD를 표시합니다.",
                ["Speeds up the appearance of menus and submenus by lowering the default delay. This improves the perceived responsiveness of the UI."] = "기본 지연 시간을 낮춰 메뉴와 하위 메뉴가 더 빨리 나타나도록 합니다.",
                ["Disables the Windows network throttling mechanism to potentially improve performance for streaming, gaming, or real-time applications."] = "Windows 네트워크 스로틀링 메커니즘을 비활성화해 스트리밍, 게임, 실시간 앱의 성능 향상을 기대할 수 있습니다.",
                ["This feature reduces the WaitToKillServiceTimeout value, which speeds up the shutdown process by reducing the time Windows waits for services to stop."] = "WaitToKillServiceTimeout 값을 줄여 서비스 종료 대기 시간을 단축하고, 결과적으로 시스템 종료를 빠르게 합니다.",
                ["Enhances system responsiveness by prioritizing CPU resources for foreground tasks, improving performance during active use."] = "전경 작업에 CPU 자원을 더 우선 배분해 사용 중 체감 응답성을 높입니다.",
                ["Adds 'End Task' to the Windows 11 taskbar context menu, allowing you to directly kill unresponsive apps."] = "Windows 11 작업 표시줄 컨텍스트 메뉴에 '작업 끝내기'를 추가해 응답 없는 앱을 바로 종료할 수 있게 합니다.",
                ["This method allows you to see what processes are hanging when shutting down and turning on the machine."] = "시스템 종료나 시작 시 어떤 프로세스가 지연되고 있는지 더 자세한 상태 메시지로 보여줍니다.",
                ["This feature disables Bing integration in Windows Search."] = "Windows 검색의 Bing 통합을 비활성화합니다.",
                ["This feature enables Dark Mode for apps in Windows 11."] = "Windows 11 앱에 다크 모드를 적용합니다.",
                ["This feature enables Dark Mode for Windows system UI (e.g., taskbar, start menu)."] = "Windows 시스템 UI(작업 표시줄, 시작 메뉴 등)에 다크 모드를 적용합니다.",
                ["This feature will enable full context menus"] = "전체 컨텍스트 메뉴를 사용하도록 설정합니다.",
                ["This feature will disable the personalized lock screen."] = "개인 맞춤 잠금 화면을 비활성화합니다.",
                ["This feature disables Bing search and web suggestions in the Windows Start Menu."] = "Windows 시작 메뉴의 Bing 검색과 웹 제안을 비활성화합니다.",
                ["This feature will hide search box on taskbar"] = "작업 표시줄 검색 상자를 숨깁니다.",
                ["This feature will hide Most used apps in start menu for all users"] = "모든 사용자에 대해 시작 메뉴의 자주 사용하는 앱 영역을 숨깁니다.",
                ["This feature will hide the Task view button on taskbar"] = "작업 표시줄의 작업 보기 버튼을 숨깁니다.",
                ["This feature disables the Snap Assist flyout, which appears when you snap a window."] = "창을 스냅할 때 나타나는 Snap Assist 플라이아웃을 비활성화합니다.",
                ["This feature will allow pinning more Apps on start menu"] = "시작 메뉴에 더 많은 앱을 고정할 수 있게 합니다.",
                ["This feature will align the Start button to left"] = "시작 버튼을 왼쪽으로 정렬합니다.",
                ["This feature disables transparency effects for Start menu, taskbar, and other surfaces."] = "시작 메뉴, 작업 표시줄 등의 투명 효과를 비활성화합니다.",

                ["&Analyze"] = "분석(&A)",
                ["Analyze"] = "분석",
                ["Fix"] = "적용",
                ["Restore"] = "복원",
                ["Help"] = "도움말",
                ["Applications"] = "앱",
                ["Run &Fixer"] = "선택 항목 적용(&F)",
                ["Checking your system.."] = "시스템 확인 중...",
                ["&Restore"] = "복원(&R)",
                ["Check for updates..."] = "업데이트 확인...",
                ["&Tools"] = "도구(&T)",
                ["&Fixer"] = "최적화(&F)",
                ["Select all"] = "모두 선택",
                ["No analysis yet"] = "아직 분석하지 않았습니다",
                ["Settings"] = "설정",
                ["About"] = "정보",
                ["Features "] = "실험 기능",
                ["Donate"] = "후원",
                ["You can download the latest version, report bugs and submit feature requests at the following GitHub page."] = "최신 버전을 내려받고 버그를 제보하거나 기능을 요청하려면 아래 GitHub 페이지를 이용하세요.",
                ["Plugins Gallery (App restart needed after install)"] = "플러그인 갤러리 (설치 후 앱 재시작 필요)",
                ["Install"] = "설치",
                ["Edit"] = "편집",
                ["Remove"] = "제거",
                ["Submit Plugin"] = "플러그인 제출",
                ["Update All"] = "모두 업데이트",
                ["Search"] = "검색",
                ["Usage notes"] = "사용 안내",
                ["Plugin"] = "플러그인",
                ["Installed"] = "설치됨",
                ["Type"] = "유형",
                ["Basic settings"] = "기본 설정",
                ["Save all settings to INI file"] = "모든 설정을 INI 파일에 저장",
                ["Activate Plugins for PowerShell Tooling (Super Plugins)"] = "PowerShell 플러그인 기능 활성화 (슈퍼 플러그인)",
                ["Download optional icons to enhance navigation UI"] = "탐색 UI를 꾸밀 추가 아이콘 다운로드",
                ["ViVe Tool"] = "ViVe Tool",
                ["More infos"] = "추가 정보",
                ["Custom Ids"] = "사용자 지정 ID",
                ["Apply selected"] = "선택 항목 적용",
                ["Apply Custom"] = "사용자 지정 적용",
                ["Feature"] = "기능",
                ["Status"] = "상태",
                ["Info"] = "정보",
                ["Unknown"] = "알 수 없음",
                ["Disabled"] = "비활성화됨",
                ["All Enabled"] = "모두 활성화됨",
                ["Partially Enabled"] = "일부 활성화됨",
                ["Yes"] = "예",
                ["No"] = "아니오",
                ["Updated"] = "업데이트됨",
                ["Powershell"] = "PowerShell",
                ["Other"] = "기타",
                ["Enable experimental and hidden features (Disabled)"] = "실험 및 숨김 기능 활성화 (비활성화됨)",
                ["Enable experimental and hidden features (Enabled)"] = "실험 및 숨김 기능 활성화 (활성화됨)",
                ["Enable the redesigned Windows 11 Start menu"] = "새로운 Windows 11 시작 메뉴 사용",
                ["Enable Text extractor in Snipping Tool"] = "캡처 도구의 텍스트 추출 사용",
                ["Enable Drag Tray Share UI"] = "드래그 트레이 공유 UI 사용",

                ["Select an action..."] = "작업 선택...",
                ["Analyze log online (recommended)"] = "로그 온라인 분석 (권장)",
                ["Copy log to clipboard"] = "로그를 클립보드로 복사",
                ["Clear log"] = "로그 지우기",
                ["The log has been copied to the clipboard.\nClick “Paste log from clipboard” on the log analyzer page, or simply press CTRL+V,\nto insert it into the analyzer."] = "로그가 클립보드에 복사되었습니다.\n로그 분석기 페이지에서 '클립보드의 로그 붙여넣기'를 누르거나 CTRL+V를 눌러 붙여넣으세요.",
                ["Log copied"] = "로그 복사됨",
                ["Please select an amount and a currency."] = "금액과 통화를 선택하세요.",
                ["Error loading plugins: "] = "플러그인을 불러오는 중 오류가 발생했습니다: ",
                ["Please check one or more plugins to download."] = "다운로드할 플러그인을 하나 이상 선택하세요.",
                ["All plugins updated."] = "모든 플러그인이 업데이트되었습니다.",
                ["No plugins selected."] = "선택된 플러그인이 없습니다.",
                ["Selected plugins removed."] = "선택한 플러그인을 제거했습니다.",
                ["Please select a plugin first."] = "먼저 플러그인을 선택하세요.",
                ["Plugin file not found. Please install the plugin first."] = "플러그인 파일을 찾을 수 없습니다. 먼저 플러그인을 설치하세요.",
                ["Could not open plugin: "] = "플러그인을 열 수 없습니다: ",
                ["Info: "] = "정보: ",
                ["By default, buttons have no icons to reduce app size. Enable this to download and display navigation icons.\nWould you like to install it now?"] = "기본값으로는 앱 크기를 줄이기 위해 버튼 아이콘이 포함되어 있지 않습니다.\n이 옵션을 켜면 탐색 아이콘을 내려받아 표시합니다.\n지금 설치하시겠습니까?",
                ["Icons Pack Detected"] = "아이콘 팩",
                ["All icons have been successfully installed in the 'icons' folder!\n\n💖 Love CrapFixer? Consider supporting me with a small donation to keep this tool alive and improving!"] = "'icons' 폴더에 모든 아이콘이 설치되었습니다.",
                ["Icons Installed"] = "아이콘 설치 완료",
                ["❌ An error occurred while downloading the icons:\n"] = "❌ 아이콘 다운로드 중 오류가 발생했습니다:\n",
                ["Download Failed"] = "다운로드 실패",
                ["ViVeTool not found. Please ensure it is installed in the plugins folder."] = "ViVeTool을 찾을 수 없습니다. plugins 폴더에 설치되어 있는지 확인하세요.",
                ["Error"] = "오류",
                ["Features have been applied."] = "기능 적용이 완료되었습니다.",
                ["Done"] = "완료",
                ["This plugin uses ViVeTool to enable hidden Windows features.\nPlease download ViVeTool (e.g. 'ViVeTool-v0.3.x-IntelAmd') from:\nhttps://github.com/thebookisclosed/ViVe/releases\nExtract it and place the contents into a subfolder inside the 'plugins' directory.\n\n"] = "이 기능은 ViVeTool을 사용해 Windows의 숨겨진 기능을 활성화합니다.\n아래 주소에서 ViVeTool(예: 'ViVeTool-v0.3.x-IntelAmd')을 내려받은 뒤:\nhttps://github.com/thebookisclosed/ViVe/releases\n압축을 풀고 내용을 'plugins' 폴더 안의 하위 폴더에 넣어 주세요.\n",
                ["Please enter one or more feature IDs."] = "기능 ID를 하나 이상 입력하세요.",
                ["Invalid Input"] = "잘못된 입력",
                ["No valid IDs found."] = "유효한 ID를 찾지 못했습니다.",
                ["Confirm Action"] = "작업 확인",
                ["Custom feature action sent to ViVeTool."] = "사용자 지정 기능 작업을 ViVeTool에 전달했습니다.",
                ["Using built-in bloatware list."] = "내장 블로트웨어 목록을 사용합니다.",
                ["🔎 Plugin ready: CFEnhancer (external bloatware list)"] = "🔎 플러그인 준비됨: CFEnhancer (외부 블로트웨어 목록)",
                ["↩️ All selected features have been restored."] = "↩️ 선택한 모든 기능을 복원했습니다.",
                ["Restore Selected Features"] = "선택한 기능 복원",
                ["⚠️ This will restore all selected features to their original state.\nChanges made by previous configurations may be reverted.\n\nAre you sure you want to proceed?"] = "⚠️ 선택한 모든 기능을 원래 상태로 되돌립니다.\n기존 설정에서 바뀐 내용도 함께 복원될 수 있습니다.\n\n계속하시겠습니까?",
                ["Bloatware apps detected:"] = "블로트웨어 앱이 감지되었습니다:",
                ["✅ No Microsoft Store bloatware apps found."] = "✅ Microsoft Store 블로트웨어 앱이 없습니다.",
                ["App cleanup complete."] = "앱 정리가 완료되었습니다.",
                ["📦 Checking all available updates via winget..."] = "📦 winget으로 사용 가능한 업데이트를 확인하는 중...",
                ["This may take a while, please be patient."] = "시간이 조금 걸릴 수 있습니다. 잠시만 기다려 주세요.",
                ["Winget upgrades cannot be undone."] = "Winget 업그레이드는 되돌릴 수 없습니다.",
                ["Restore is not possible for this plugin."] = "이 플러그인은 복원할 수 없습니다.",
                ["Information"] = "정보",
                ["Plugin Activation Warning"] = "플러그인 실행 경고",
                ["No additional information available."] = "추가 정보가 없습니다.",
                ["Would you like to search online for more information about this feature?"] = "이 기능에 대한 추가 정보를 온라인에서 검색하시겠습니까?",
                ["Online Help"] = "온라인 도움말",
                ["⚠️ No feature or plugin selected, or help info unavailable."] = "⚠️ 선택된 기능 또는 플러그인이 없거나 도움말 정보를 사용할 수 없습니다.",
            };

        private static readonly (string From, string To)[] FragmentTranslations =
        {
            (" | Value: ", " | 값: "),
            (" |Value: ", " | 값: "),
            (" | Values: ", " | 값들: "),
            (" | Recommended Value: ", " | 권장값: "),
            (" | Recommended: ", " | 권장값: "),
            (" | Suggested Value: ", " | 권장값: "),
            (" | Suggestion: ", " | 권장값: "),
            (" | Set to: ", " | 설정값: "),
            ("Temp folder size: ", "임시 폴더 크기: "),
            (" (including cleanmgr /sagerun:1 in the next run)", " (다음 실행 시 cleanmgr /sagerun:1 포함)"),
            ("(Dark mode – preferred for a modern look, but up to you)", "(다크 모드 권장)"),
            ("(Dark mode – easy on the eyes, but totally your call)", "(눈이 편한 다크 모드 권장)"),
            ("(Task View off – cleaner taskbar, unless you use it often)", "(작업 보기 비활성화 권장)"),
            ("(Left – feels like home if you're coming from Windows 10)", "(Windows 10 스타일을 원하면 왼쪽 정렬 권장)"),
            ("(No transparency – smoother performance, still stylish)", "(투명 효과 끄기 권장)"),
            ("(Recall off – protect your privacy, prevent AI from accessing personal data)", "(개인정보 보호를 위해 Recall 끄기 권장)"),
            ("(disables Click to Do, removing it from context menus). ", "(Click to Do를 끄고 컨텍스트 메뉴에서 제거합니다). "),
            ("Note: This setting only applies on Copilot+ PCs with Windows 11 24H2 or newer.", "참고: 이 설정은 Windows 11 24H2 이상이 설치된 Copilot+ PC에서만 적용됩니다."),
            ("(Checked against ", "(시스템 앱 "),
            (" apps from the system)", "개 기준으로 확인)"),
            ("❌ [ Bloatware ] ", "❌ [ 블로트웨어 ] "),
            ("\n🧩 APPS ANALYSIS", "\n🧩 앱 분석"),
            ("\n🔌 PLUGIN ANALYSIS", "\n🔌 플러그인 분석"),
            ("🔎 ANALYSIS COMPLETE", "🔎 분석 완료"),
            ("Summary: ", "요약: "),
            (" checked settings are OK; ", "개의 선택 설정 중 "),
            (" require attention.", "개는 점검이 필요합니다."),
            (" - Not configured as recommended.", " - 권장 설정과 다릅니다."),
            (" - Fixed", " - 적용 완료"),
            (" - Restore failed", " - 복원 실패"),
            (" - Restored", " - 복원 완료"),
            ("Feature: ", "기능: "),
            ("Plugin: ", "플러그인: "),
            (" is properly configured.", " 정상적으로 구성되어 있습니다."),
            (" requires attention.", " 점검이 필요합니다."),
            ("🔎 Analyzing Feature: ", "🔎 기능 분석 중: "),
            ("🔧 Fixing Feature: ", "🔧 기능 적용 중: "),
            ("↩️ Restoring Feature: ", "↩️ 기능 복원 중: "),
            ("[PS Output] ", "[PS 출력] "),
            ("[PS Error] ", "[PS 오류] "),
            ("✅ Script executed: ", "✅ 스크립트 실행됨: "),
            ("❌ Error executing script: ", "❌ 스크립트 실행 오류: "),
            ("🔎 Plugin ready: [PS] ", "🔎 플러그인 준비됨: [PS] "),
            ("🔧 Running Do command for plugin: ", "🔧 플러그인 Do 명령 실행: "),
            ("Do Output:\n", "Do 출력:\n"),
            ("✅ Fix applied successfully.", "✅ 적용이 완료되었습니다."),
            ("❌ Fix failed.", "❌ 적용에 실패했습니다."),
            ("🔧 No Do command found, executing full script.", "🔧 Do 명령이 없어 전체 스크립트를 실행합니다."),
            ("♻️ Running Undo command for plugin: ", "♻️ 플러그인 Undo 명령 실행: "),
            ("Undo Output:\n", "Undo 출력:\n"),
            ("✅ Restore successful.", "✅ 복원 완료"),
            ("❌ Restore failed.", "❌ 복원 실패"),
            ("⚠️ No Undo command found. Restore not possible.", "⚠️ Undo 명령이 없어 복원할 수 없습니다."),
            ("Plugin Help: ", "플러그인 도움말: "),
            ("Error reading external bloatware file: ", "외부 블로트웨어 목록을 읽는 중 오류가 발생했습니다: "),
            ("⚠️ The bloatware radar stays basic for now 🧠. Get the enhanced detection list from Options > Plugins > CFEnhancer plugin", "⚠️ 현재는 기본 블로트웨어 탐지만 사용 중입니다. 옵션 > 플러그인에서 CFEnhancer 플러그인을 설치하면 감지 목록이 확장됩니다."),
            ("Successfully uninstalled app: ", "앱 제거 성공: "),
            ("Failed to uninstall appe: ", "앱 제거 실패: "),
            ("Error during uninstalling app ", "앱 제거 중 오류: "),
            ("🗑️ Removing app: ", "🗑️ 앱 제거 중: "),
            ("🗑️ Removed Store App: ", "🗑️ Store 앱 제거됨: "),
            ("⚠️ Failed to remove Store App: ", "⚠️ Store 앱 제거 실패: "),
            ("Registry check failed for ", "레지스트리 확인 실패: "),
            ("Failed to open GitHub page: ", "GitHub 페이지를 여는 데 실패했습니다: "),
            ("Restarting Windows Explorer to apply UI changes...", "UI 변경 적용을 위해 Windows 탐색기를 다시 시작합니다..."),
            ("Explorer restarted successfully.", "탐색기를 다시 시작했습니다."),
            ("Failed to restart Explorer: ", "탐색기 재시작 실패: "),
            ("Winget upgrade check:\n", "Winget 업그레이드 확인:\n"),
            ("Winget check failed: ", "Winget 확인 실패: "),
            ("Failed to run winget upgrade: ", "Winget 업그레이드 실행 실패: "),
            ("File Explorer Ads disabled", "파일 탐색기 광고를 비활성화했습니다."),
            ("File Explorer Ads enabled", "파일 탐색기 광고를 다시 활성화했습니다."),
            ("'Ask Copilot' context menu entry has been blocked.", "'Ask Copilot' 컨텍스트 메뉴 항목을 차단했습니다."),
            ("'Ask Copilot' context menu entry has been restored.", "'Ask Copilot' 컨텍스트 메뉴 항목을 복원했습니다."),
            ("You've even disabled system-wide Snapshots for all users now.", "이제 모든 사용자에 대해 시스템 전체 Snapshot 기능이 비활성화되었습니다."),
            ("Error in ", "오류: "),
            ("Error occurred while ", "오류: "),
            ("Error undoing ", "되돌리는 중 오류: "),
            ("Error blocking ", "차단 중 오류: "),
            ("Error restoring ", "복원 중 오류: "),
            ("Failed to enable End Task: ", "작업 끝내기 활성화 실패: "),
            ("Failed to disable End Task: ", "작업 끝내기 비활성화 실패: "),
            ("Code red in ", "오류: "),
            ("OS info unavailable: ", "OS 정보를 가져올 수 없습니다: "),
            ("OS not supported", "지원되지 않는 OS"),
            ("Failed to open link:\n", "링크를 열 수 없습니다:\n"),
            ("Invalid ID: '", "잘못된 ID: '"),
        };

        public static string T(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return text;
            }

            if (ExactTranslations.TryGetValue(text, out string translated))
            {
                return translated;
            }

            return TranslateRuntimeText(text);
        }

        public static string TreeText(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                return text;
            }

            return T(text.Trim());
        }

        public static string Detail(string text) => TranslateRuntimeText(text);

        public static string TranslateRuntimeText(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return text;
            }

            if (ExactTranslations.TryGetValue(text, out string translated))
            {
                return translated;
            }

            string result = text;
            foreach (var pair in FragmentTranslations)
            {
                result = result.Replace(pair.From, pair.To);
            }

            return result;
        }
    }
}
